### ISSUE TITLE
About images are broken

### ISSUE THREAD

**Issue by alperozisik** [smartface/smartface.about#2]
As seen in the pictue about display has been broken
<img width="671" alt="screen shot 2016-03-29 at 15 49 52" src="https://cloud.githubusercontent.com/assets/7248325/14108477/5313dd2c-f5c6-11e5-83d2-5a8727c69ae0.png">

**Comment by helmas** [comment]
In fact there are some css styles that re-sizes the images you mentioned above. In css file, smartface logo has been set as width: 213px, height: 38px and also for close button. I have to test them in test environment, and have to type some css styles to solve those issues. Can you provide me?

**Comment by alperozisik** [comment]
Create a C9 workspace and watch me configure it.
Then you have to do it your self
